### ISSUE TITLE
code license?

### ISSUE THREAD

**Issue by ErikMoll** [brianreinhold/NordicPHDs#1]
There is a licenses.txt file in the repo that states:
See the top of each source file for the license under which the file is released.

This is fine for files that are coming from existing repositories, like the Nordic SDK files.
However, newly developed source files, like "handleSpecializations.c", do not have a license section.

Under what license can they be used?
Can this information be placed in the repo and/or in these files?

A suggestion is to use the MIT license - "use freely", "as is", "no guarantees": https://opensource.org/license/mit/

**Comment by brianreinhold** [comment]
added
